// Generated by gencpp from file uno/add.msg
// DO NOT EDIT!


#ifndef UNO_MESSAGE_ADD_H
#define UNO_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <uno/addRequest.h>
#include <uno/addResponse.h>


namespace uno
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace uno


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uno::add > {
  static const char* value()
  {
    return "210a18f816d5b88becb133b82fae0c4c";
  }

  static const char* value(const ::uno::add&) { return value(); }
};

template<>
struct DataType< ::uno::add > {
  static const char* value()
  {
    return "uno/add";
  }

  static const char* value(const ::uno::add&) { return value(); }
};


// service_traits::MD5Sum< ::uno::addRequest> should match
// service_traits::MD5Sum< ::uno::add >
template<>
struct MD5Sum< ::uno::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uno::add >::value();
  }
  static const char* value(const ::uno::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uno::addRequest> should match
// service_traits::DataType< ::uno::add >
template<>
struct DataType< ::uno::addRequest>
{
  static const char* value()
  {
    return DataType< ::uno::add >::value();
  }
  static const char* value(const ::uno::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uno::addResponse> should match
// service_traits::MD5Sum< ::uno::add >
template<>
struct MD5Sum< ::uno::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uno::add >::value();
  }
  static const char* value(const ::uno::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uno::addResponse> should match
// service_traits::DataType< ::uno::add >
template<>
struct DataType< ::uno::addResponse>
{
  static const char* value()
  {
    return DataType< ::uno::add >::value();
  }
  static const char* value(const ::uno::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNO_MESSAGE_ADD_H
